spring.application.name=ai
spring.datasource.url=jdbc:mysql://mysql-aiapp-quysssss.c.aivencloud.com:25845/ai?sslMode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true